generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Budget
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          budget
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        year: { label: Год }
        quarter: { label: Квартал }
        plan: { label: Бюджет по плану }
      list:    ~
      filter:  ~
      form:    ~
      edit:   
        title: Планируемый бюджет на %%quarter%%-й квартал %%year%% года
      new:     
        title: Добавление бюджета
