<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActivityInfoFieldsData', 'doctrine');

/**
 * BaseActivityInfoFieldsData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $activity_id
 * @property integer $field_id
 * @property string $description
 * @property interger $order_num
 * @property boolean $status
 * 
 * @method integer                getId()          Returns the current record's "id" value
 * @method integer                getActivityId()  Returns the current record's "activity_id" value
 * @method integer                getFieldId()     Returns the current record's "field_id" value
 * @method string                 getDescription() Returns the current record's "description" value
 * @method interger               getOrderNum()    Returns the current record's "order_num" value
 * @method boolean                getStatus()      Returns the current record's "status" value
 * @method ActivityInfoFieldsData setId()          Sets the current record's "id" value
 * @method ActivityInfoFieldsData setActivityId()  Sets the current record's "activity_id" value
 * @method ActivityInfoFieldsData setFieldId()     Sets the current record's "field_id" value
 * @method ActivityInfoFieldsData setDescription() Sets the current record's "description" value
 * @method ActivityInfoFieldsData setOrderNum()    Sets the current record's "order_num" value
 * @method ActivityInfoFieldsData setStatus()      Sets the current record's "status" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityInfoFieldsData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_info_fields_data');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('field_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => 'clob',
             'length' => 255,
             ));
        $this->hasColumn('order_num', 'interger', null, array(
             'type' => 'interger',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}