<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LegalPerson', 'vw_general');

/**
 * BaseLegalPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $legal_address
 * @property string $INN
 * @property string $KPP
 * @property string $OKPO
 * @property string $transactional_account
 * @property string $correspondent_account
 * @property string $BIK
 * @property string $bank_name
 * @property Doctrine_Collection $Dealer
 * 
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getLegalAddress()          Returns the current record's "legal_address" value
 * @method string              getINN()                   Returns the current record's "INN" value
 * @method string              getKPP()                   Returns the current record's "KPP" value
 * @method string              getOKPO()                  Returns the current record's "OKPO" value
 * @method string              getTransactionalAccount()  Returns the current record's "transactional_account" value
 * @method string              getCorrespondentAccount()  Returns the current record's "correspondent_account" value
 * @method string              getBIK()                   Returns the current record's "BIK" value
 * @method string              getBankName()              Returns the current record's "bank_name" value
 * @method Doctrine_Collection getDealer()                Returns the current record's "Dealer" collection
 * @method LegalPerson         setName()                  Sets the current record's "name" value
 * @method LegalPerson         setLegalAddress()          Sets the current record's "legal_address" value
 * @method LegalPerson         setINN()                   Sets the current record's "INN" value
 * @method LegalPerson         setKPP()                   Sets the current record's "KPP" value
 * @method LegalPerson         setOKPO()                  Sets the current record's "OKPO" value
 * @method LegalPerson         setTransactionalAccount()  Sets the current record's "transactional_account" value
 * @method LegalPerson         setCorrespondentAccount()  Sets the current record's "correspondent_account" value
 * @method LegalPerson         setBIK()                   Sets the current record's "BIK" value
 * @method LegalPerson         setBankName()              Sets the current record's "bank_name" value
 * @method LegalPerson         setDealer()                Sets the current record's "Dealer" collection
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLegalPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('legal_persons');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('legal_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('INN', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('KPP', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('OKPO', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('transactional_account', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('correspondent_account', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('BIK', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('bank_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Dealer', array(
             'local' => 'id',
             'foreign' => 'company_id'));
    }
}