<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActivityExtendedStatisticSections', 'doctrine');

/**
 * BaseActivityExtendedStatisticSections
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property integer $activity_id
 * @property integer $status
 * @property string $header
 * 
 * @method integer                           getId()          Returns the current record's "id" value
 * @method integer                           getParentId()    Returns the current record's "parent_id" value
 * @method integer                           getActivityId()  Returns the current record's "activity_id" value
 * @method integer                           getStatus()      Returns the current record's "status" value
 * @method string                            getHeader()      Returns the current record's "header" value
 * @method ActivityExtendedStatisticSections setId()          Sets the current record's "id" value
 * @method ActivityExtendedStatisticSections setParentId()    Sets the current record's "parent_id" value
 * @method ActivityExtendedStatisticSections setActivityId()  Sets the current record's "activity_id" value
 * @method ActivityExtendedStatisticSections setStatus()      Sets the current record's "status" value
 * @method ActivityExtendedStatisticSections setHeader()      Sets the current record's "header" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityExtendedStatisticSections extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_extended_statistic_sections');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('position', 'integer', null, array(
            'type' => 'integer',
            'notnull' => false,
        ));
        $this->hasColumn('header', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
            'type' => 'clob',
            'notnull' => false,
        ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
 
        $this->hasMany('ActivityExtendedStatisticFields as Fields', array(
             'local' => 'id',
             'foreign' => 'parent_id'));       
    }
}
