<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DealersBudgetsFiles', 'doctrine');

/**
 * BaseDealersBudgetsFiles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $file_name
 * @property integer $total_dealers
 * @property integer $year
 * @property decimal $budget_of_year
 * @property decimal $budget_of_q1
 * @property decimal $budget_of_q2
 * @property decimal $budget_of_q3
 * @property decimal $budget_of_q4
 * @property boolean $status
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getFileName()       Returns the current record's "file_name" value
 * @method integer             getTotalDealers()   Returns the current record's "total_dealers" value
 * @method integer             getYear()           Returns the current record's "year" value
 * @method decimal             getBudgetOfYear()   Returns the current record's "budget_of_year" value
 * @method decimal             getBudgetOfQ1()     Returns the current record's "budget_of_q1" value
 * @method decimal             getBudgetOfQ2()     Returns the current record's "budget_of_q2" value
 * @method decimal             getBudgetOfQ3()     Returns the current record's "budget_of_q3" value
 * @method decimal             getBudgetOfQ4()     Returns the current record's "budget_of_q4" value
 * @method boolean             getStatus()         Returns the current record's "status" value
 * @method DealersBudgetsFiles setId()             Sets the current record's "id" value
 * @method DealersBudgetsFiles setFileName()       Sets the current record's "file_name" value
 * @method DealersBudgetsFiles setTotalDealers()   Sets the current record's "total_dealers" value
 * @method DealersBudgetsFiles setYear()           Sets the current record's "year" value
 * @method DealersBudgetsFiles setBudgetOfYear()   Sets the current record's "budget_of_year" value
 * @method DealersBudgetsFiles setBudgetOfQ1()     Sets the current record's "budget_of_q1" value
 * @method DealersBudgetsFiles setBudgetOfQ2()     Sets the current record's "budget_of_q2" value
 * @method DealersBudgetsFiles setBudgetOfQ3()     Sets the current record's "budget_of_q3" value
 * @method DealersBudgetsFiles setBudgetOfQ4()     Sets the current record's "budget_of_q4" value
 * @method DealersBudgetsFiles setStatus()         Sets the current record's "status" value
 * 
 * @package    Marketing Aftersales NFZ
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDealersBudgetsFiles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dealers_budgets_files');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('file_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('total_dealers', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('budget_of_year', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('budget_of_q1', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('budget_of_q2', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('budget_of_q3', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('budget_of_q4', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}