<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DealersTypes', 'doctrine');

/**
 * BaseDealersTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * 
 * @method integer      getId()   Returns the current record's "id" value
 * @method string       getName() Returns the current record's "name" value
 * @method DealersTypes setId()   Sets the current record's "id" value
 * @method DealersTypes setName() Sets the current record's "name" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDealersTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dealers_types');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}