<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AgreementModelCategories', 'doctrine');

/**
 * BaseAgreementModelCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property enum $work_type
 * @property boolean $status
 * @property Doctrine_Collection $AgreementModelCategoriesFields
 * 
 * @method integer                  getId()                             Returns the current record's "id" value
 * @method string                   getName()                           Returns the current record's "name" value
 * @method string                   getDescription()                    Returns the current record's "description" value
 * @method enum                     getWorkType()                       Returns the current record's "work_type" value
 * @method boolean                  getStatus()                         Returns the current record's "status" value
 * @method Doctrine_Collection      getAgreementModelCategoriesFields() Returns the current record's "AgreementModelCategoriesFields" collection
 * @method AgreementModelCategories setId()                             Sets the current record's "id" value
 * @method AgreementModelCategories setName()                           Sets the current record's "name" value
 * @method AgreementModelCategories setDescription()                    Sets the current record's "description" value
 * @method AgreementModelCategories setWorkType()                       Sets the current record's "work_type" value
 * @method AgreementModelCategories setStatus()                         Sets the current record's "status" value
 * @method AgreementModelCategories setAgreementModelCategoriesFields() Sets the current record's "AgreementModelCategoriesFields" collection
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgreementModelCategories extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agreement_model_categories');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('identifier', 'string', 255, array(
            'type' => 'string',
            'length' => 255,
            'notnull' => true,
        ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('work_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'manager',
              1 => 'manager_designer',
             ),
             ));
        $this->hasColumn('is_blank', 'boolean', null, array(
            'type' => 'boolean',
            'notnull' => true,
            'default' => false,
        ));
        $this->hasColumn('days_to_agreement', 'integer', 2, array(
            'type' => 'integer',
            'notnull' => true,
            'default' => 1,
        ));
        $this->hasColumn('days_to_agreement_report', 'integer', 2, array(
            'type' => 'integer',
            'notnull' => true,
            'default' => 5,
        ));
        $this->hasColumn('position', 'integer', 11, array(
            'type' => 'integer',
            'notnull' => true,
            'default' => 0,
        ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();

        $this->hasMany('AgreementModelType as CategoryTypes', array(
            'local' => 'id',
            'foreign' => 'parent_category_id',
            'cascade' => array(
                0 => 'delete',
            )));

        $this->hasMany('AgreementModelField as Fields', array(
            'local' => 'id',
            'foreign' => 'parent_category_id',
            'cascade' => array(
                0 => 'delete',
            )
        ));

        $this->hasMany('AgreementModelCategoriesAllowedMimeTypes as MimeTypes', array(
            'local' => 'id',
            'foreign' => 'category_id',
            'cascade' => array(
                0 => 'delete',
            )));
    }
}
