<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DiscussionOnline', 'doctrine');

/**
 * BaseDiscussionOnline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $discussion_id
 * @property integer $user_id
 * @property Discussion $Discussion
 * @property User $User
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getDiscussionId()  Returns the current record's "discussion_id" value
 * @method integer          getUserId()        Returns the current record's "user_id" value
 * @method Discussion       getDiscussion()    Returns the current record's "Discussion" value
 * @method User             getUser()          Returns the current record's "User" value
 * @method DiscussionOnline setId()            Sets the current record's "id" value
 * @method DiscussionOnline setDiscussionId()  Sets the current record's "discussion_id" value
 * @method DiscussionOnline setUserId()        Sets the current record's "user_id" value
 * @method DiscussionOnline setDiscussion()    Sets the current record's "Discussion" value
 * @method DiscussionOnline setUser()          Sets the current record's "User" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiscussionOnline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('discussion_online');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('discussion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Discussion', array(
             'local' => 'discussion_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}