<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Budget', 'doctrine');

/**
 * BaseBudget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dealer_id
 * @property integer $year
 * @property integer $quarter
 * @property decimal $plan
 * @property Dealer $Dealer
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getDealerId()  Returns the current record's "dealer_id" value
 * @method integer getYear()      Returns the current record's "year" value
 * @method integer getQuarter()   Returns the current record's "quarter" value
 * @method decimal getPlan()      Returns the current record's "plan" value
 * @method Dealer  getDealer()    Returns the current record's "Dealer" value
 * @method Budget  setId()        Sets the current record's "id" value
 * @method Budget  setDealerId()  Sets the current record's "dealer_id" value
 * @method Budget  setYear()      Sets the current record's "year" value
 * @method Budget  setQuarter()   Sets the current record's "quarter" value
 * @method Budget  setPlan()      Sets the current record's "plan" value
 * @method Budget  setDealer()    Sets the current record's "Dealer" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBudget extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('budget');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('dealer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('year', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('quarter', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('plan', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('orderBy', 'year desc,quarter desc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dealer', array(
             'local' => 'dealer_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}