<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VwUser', 'vw_general');

/**
 * BaseVwUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property integer $person_id
 * @property NaturalPerson $Person
 * 
 * @method integer       getId()        Returns the current record's "id" value
 * @method string        getEmail()     Returns the current record's "email" value
 * @method integer       getPersonId()  Returns the current record's "person_id" value
 * @method NaturalPerson getPerson()    Returns the current record's "Person" value
 * @method VwUser        setId()        Sets the current record's "id" value
 * @method VwUser        setEmail()     Sets the current record's "email" value
 * @method VwUser        setPersonId()  Sets the current record's "person_id" value
 * @method VwUser        setPerson()    Sets the current record's "Person" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVwUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NaturalPerson as Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));
    }
}