<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sp1User', 'doctrine');

/**
 * BaseSp1User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $dealer_number
 * @property string $company
 * @property string $post
 * @property string $family
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $mobile_phone
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method string  getDealerNumber()  Returns the current record's "dealer_number" value
 * @method string  getCompany()       Returns the current record's "company" value
 * @method string  getPost()          Returns the current record's "post" value
 * @method string  getFamily()        Returns the current record's "family" value
 * @method string  getName()          Returns the current record's "name" value
 * @method string  getEmail()         Returns the current record's "email" value
 * @method string  getPhone()         Returns the current record's "phone" value
 * @method string  getMobilePhone()   Returns the current record's "mobile_phone" value
 * @method Sp1User setId()            Sets the current record's "id" value
 * @method Sp1User setDealerNumber()  Sets the current record's "dealer_number" value
 * @method Sp1User setCompany()       Sets the current record's "company" value
 * @method Sp1User setPost()          Sets the current record's "post" value
 * @method Sp1User setFamily()        Sets the current record's "family" value
 * @method Sp1User setName()          Sets the current record's "name" value
 * @method Sp1User setEmail()         Sets the current record's "email" value
 * @method Sp1User setPhone()         Sets the current record's "phone" value
 * @method Sp1User setMobilePhone()   Sets the current record's "mobile_phone" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSp1User extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sp1_user');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('dealer_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('company', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('post', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('family', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mobile_phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}