<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActivityQuarters', 'doctrine');

/**
 * BaseActivityQuarters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activity_id
 * @property integer $quarter_id
 * 
 * @method integer          getActivityId()  Returns the current record's "activity_id" value
 * @method integer          getQuarterId()   Returns the current record's "quarter_id" value
 * @method ActivityQuarters setActivityId()  Sets the current record's "activity_id" value
 * @method ActivityQuarters setQuarterId()   Sets the current record's "quarter_id" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityQuarters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_quarters');
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('quarter_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();

        $this->hasOne('Quarters as Quarter', array(
            'local' => 'quarter_id',
            'foreign' => 'id'));
    }
}