<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AgreementDeclineReportReason', 'doctrine');

/**
 * BaseAgreementDeclineReportReason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Reports
 * 
 * @method integer                      getId()      Returns the current record's "id" value
 * @method string                       getName()    Returns the current record's "name" value
 * @method Doctrine_Collection          getReports() Returns the current record's "Reports" collection
 * @method AgreementDeclineReportReason setId()      Sets the current record's "id" value
 * @method AgreementDeclineReportReason setName()    Sets the current record's "name" value
 * @method AgreementDeclineReportReason setReports() Sets the current record's "Reports" collection
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgreementDeclineReportReason extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agreement_decline_report_reason');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AgreementModelReport as Reports', array(
             'local' => 'id',
             'foreign' => 'decline_reason_id'));
    }
}