<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DealerWorkStatisticModels', 'doctrine');

/**
 * BaseDealerWorkStatisticModels
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $model_id
 * @property float $model_cost
 * @property integer $activity_id
 * @property integer $parent_id
 * 
 * @method integer                   getId()          Returns the current record's "id" value
 * @method integer                   getModelId()     Returns the current record's "model_id" value
 * @method float                     getModelCost()   Returns the current record's "model_cost" value
 * @method integer                   getActivityId()  Returns the current record's "activity_id" value
 * @method integer                   getParentId()    Returns the current record's "parent_id" value
 * @method DealerWorkStatisticModels setId()          Sets the current record's "id" value
 * @method DealerWorkStatisticModels setModelId()     Sets the current record's "model_id" value
 * @method DealerWorkStatisticModels setModelCost()   Sets the current record's "model_cost" value
 * @method DealerWorkStatisticModels setActivityId()  Sets the current record's "activity_id" value
 * @method DealerWorkStatisticModels setParentId()    Sets the current record's "parent_id" value
 * @property AgreementModel $
 * @property Activity $
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDealerWorkStatisticModels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dealer_work_statistic_models');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('model_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('model_cost', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('model', array(
             'fields' => 
             array(
              0 => 'model_id',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AgreementModel', array(
             'local' => 'model_id',
             'foreign' => 'id'));

        $this->hasMany('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id'));
    }
}