<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AgreementMaterialField', 'doctrine');

/**
 * BaseAgreementMaterialField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $material_type_id
 * @property string $name
 * @property string $identifier
 * @property enum $type
 * @property integer $sort
 * @property string $list
 * @property AgreementMaterialType $MaterialType
 * 
 * @method integer                getId()               Returns the current record's "id" value
 * @method integer                getMaterialTypeId()   Returns the current record's "material_type_id" value
 * @method string                 getName()             Returns the current record's "name" value
 * @method string                 getIdentifier()       Returns the current record's "identifier" value
 * @method enum                   getType()             Returns the current record's "type" value
 * @method integer                getSort()             Returns the current record's "sort" value
 * @method string                 getList()             Returns the current record's "list" value
 * @method AgreementMaterialType  getMaterialType()     Returns the current record's "MaterialType" value
 * @method AgreementMaterialField setId()               Sets the current record's "id" value
 * @method AgreementMaterialField setMaterialTypeId()   Sets the current record's "material_type_id" value
 * @method AgreementMaterialField setName()             Sets the current record's "name" value
 * @method AgreementMaterialField setIdentifier()       Sets the current record's "identifier" value
 * @method AgreementMaterialField setType()             Sets the current record's "type" value
 * @method AgreementMaterialField setSort()             Sets the current record's "sort" value
 * @method AgreementMaterialField setList()             Sets the current record's "list" value
 * @method AgreementMaterialField setMaterialType()     Sets the current record's "MaterialType" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgreementMaterialField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agreement_material_field');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('material_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('identifier', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'string',
              1 => 'date',
              2 => 'select',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('sort', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('list', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('orderBy', 'sort asc, id asc');
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');

        $this->setSubClasses(array(
             'AgreementStringField' => 
             array(
              'type' => 'string',
             ),
             'AgreementDateField' => 
             array(
              'type' => 'date',
             ),
             'AgreementListField' => 
             array(
              'type' => 'list',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AgreementMaterialType as MaterialType', array(
             'local' => 'material_type_id',
             'foreign' => 'id'));
    }
}