<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ActivityInfo', 'doctrine');

/**
 * BaseActivityInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $activity_id
 * @property string $icon
 * @property string $name
 * @property clob $text
 * @property integer $sort
 * @property Activity $Activity
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getActivityId()  Returns the current record's "activity_id" value
 * @method string       getIcon()        Returns the current record's "icon" value
 * @method string       getName()        Returns the current record's "name" value
 * @method clob         getText()        Returns the current record's "text" value
 * @method integer      getSort()        Returns the current record's "sort" value
 * @method Activity     getActivity()    Returns the current record's "Activity" value
 * @method ActivityInfo setId()          Sets the current record's "id" value
 * @method ActivityInfo setActivityId()  Sets the current record's "activity_id" value
 * @method ActivityInfo setIcon()        Sets the current record's "icon" value
 * @method ActivityInfo setName()        Sets the current record's "name" value
 * @method ActivityInfo setText()        Sets the current record's "text" value
 * @method ActivityInfo setSort()        Sets the current record's "sort" value
 * @method ActivityInfo setActivity()    Sets the current record's "Activity" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_info');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('icon', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('sort', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('sort', array(
             'fields' => 
             array(
              0 => 'activity_id',
              1 => 'sort',
              2 => 'id',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('orderBy', 'sort asc, id asc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}