<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AcceptedDealerActivity', 'doctrine');

/**
 * BaseAcceptedDealerActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $activity_id
 * @property integer $dealer_id
 * @property timestamp $accept_date
 * @property Activity $Activity
 * @property Dealer $Dealer
 * 
 * @method integer                getId()          Returns the current record's "id" value
 * @method integer                getActivityId()  Returns the current record's "activity_id" value
 * @method integer                getDealerId()    Returns the current record's "dealer_id" value
 * @method timestamp              getAcceptDate()  Returns the current record's "accept_date" value
 * @method Activity               getActivity()    Returns the current record's "Activity" value
 * @method Dealer                 getDealer()      Returns the current record's "Dealer" value
 * @method AcceptedDealerActivity setId()          Sets the current record's "id" value
 * @method AcceptedDealerActivity setActivityId()  Sets the current record's "activity_id" value
 * @method AcceptedDealerActivity setDealerId()    Sets the current record's "dealer_id" value
 * @method AcceptedDealerActivity setAcceptDate()  Sets the current record's "accept_date" value
 * @method AcceptedDealerActivity setActivity()    Sets the current record's "Activity" value
 * @method AcceptedDealerActivity setDealer()      Sets the current record's "Dealer" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcceptedDealerActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accepted_dealer_activity');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dealer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('accept_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));


        $this->index('relation', array(
             'fields' => 
             array(
              0 => 'activity_id',
              1 => 'dealer_id',
             ),
             'type' => 'unique',
             ));
        $this->index('accept_date', array(
             'fields' => 
             array(
              0 => 'accept_date',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id'));

        $this->hasOne('Dealer', array(
             'local' => 'dealer_id',
             'foreign' => 'id'));
    }
}