<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DealersServiceData', 'doctrine');

/**
 * BaseDealersServiceData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $dealer_id
 * @property integer $dialog_service_id
 * @property date $start_date
 * @property date $end_date
 * 
 * @method integer            getId()                Returns the current record's "id" value
 * @method integer            getUserId()            Returns the current record's "user_id" value
 * @method integer            getDealerId()          Returns the current record's "dealer_id" value
 * @method integer            getDialogServiceId()   Returns the current record's "dialog_service_id" value
 * @method date               getStartDate()         Returns the current record's "start_date" value
 * @method date               getEndDate()           Returns the current record's "end_date" value
 * @method DealersServiceData setId()                Sets the current record's "id" value
 * @method DealersServiceData setUserId()            Sets the current record's "user_id" value
 * @method DealersServiceData setDealerId()          Sets the current record's "dealer_id" value
 * @method DealersServiceData setDialogServiceId()   Sets the current record's "dialog_service_id" value
 * @method DealersServiceData setStartDate()         Sets the current record's "start_date" value
 * @method DealersServiceData setEndDate()           Sets the current record's "end_date" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDealersServiceData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dealers_service_data');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('dealer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('dialog_service_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('end_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'accepted',
              1 => 'declined',
             ),
             'notnull' => true,
             )); 
        $this->hasColumn('declined_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();

        $this->hasOne('DealerServicesDialogs as Dialog', array(
             'local' => 'dialog_service_id',
             'foreign' => 'id'));

        $this->hasOne('Dealer', array(
             'local' => 'dealer_id',
             'foreign' => 'id'));
        
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}