<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DealerModelsTotalCost', 'doctrine');

/**
 * BaseDealerModelsTotalCost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dealer_id
 * @property integer $category_id
 * @property integer $year
 * @property integer $quarter
 * @property double $cost
 * 
 * @method integer               getId()          Returns the current record's "id" value
 * @method integer               getDealerId()    Returns the current record's "dealer_id" value
 * @method integer               getCategoryId()  Returns the current record's "category_id" value
 * @method integer               getYear()        Returns the current record's "year" value
 * @method integer               getQuarter()     Returns the current record's "quarter" value
 * @method double                getCost()        Returns the current record's "cost" value
 * @method DealerModelsTotalCost setId()          Sets the current record's "id" value
 * @method DealerModelsTotalCost setDealerId()    Sets the current record's "dealer_id" value
 * @method DealerModelsTotalCost setCategoryId()  Sets the current record's "category_id" value
 * @method DealerModelsTotalCost setYear()        Sets the current record's "year" value
 * @method DealerModelsTotalCost setQuarter()     Sets the current record's "quarter" value
 * @method DealerModelsTotalCost setCost()        Sets the current record's "cost" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDealerModelsTotalCost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dealer_models_total_cost');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('dealer_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             'notnull' => true,
             ));
        $this->hasColumn('activity_id', 'integer', 11, array(
            'type' => 'integer',
            'length' => 11,
            'notnull' => true,
        ));
        $this->hasColumn('category_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             'notnull' => true,
             ));
        $this->hasColumn('year', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             'notnull' => true,
             ));
        $this->hasColumn('quarter', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             'notnull' => true,
             ));
        $this->hasColumn('cost', 'double', 20, array(
             'type' => 'double',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('models_count', 'integer', 11, array(
            'type' => 'integer',
            'length' => 20,
            'notnull' => true,
        ));


        $this->index('dealer_models', array(
             'fields' => 
             array(
              0 => 'dealer_id',
              1 => 'category_id',
             ),
             ));
        $this->index('dealer_models_period', array(
             'fields' => 
             array(
              0 => 'year',
              1 => 'quarter',
             ),
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}
