<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DealerPlans', 'doctrine');

/**
 * BaseDealerPlans
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dealer_id
 * @property string $name
 * @property integer $plan1
 * @property integer $plan2
 * @property timestamp $last_visit_date
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method integer     getDealerId()        Returns the current record's "dealer_id" value
 * @method string      getName()            Returns the current record's "name" value
 * @method integer     getPlan1()           Returns the current record's "plan1" value
 * @method integer     getPlan2()           Returns the current record's "plan2" value
 * @method timestamp   getLastVisitDate()   Returns the current record's "last_visit_date" value
 * @method DealerPlans setId()              Sets the current record's "id" value
 * @method DealerPlans setDealerId()        Sets the current record's "dealer_id" value
 * @method DealerPlans setName()            Sets the current record's "name" value
 * @method DealerPlans setPlan1()           Sets the current record's "plan1" value
 * @method DealerPlans setPlan2()           Sets the current record's "plan2" value
 * @method DealerPlans setAddedDate()   Sets the current record's "last_visit_date" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDealerPlans extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dealer_plans');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('dealer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('plan1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('plan2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('added_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MailingList as Mailings', array(
            'local' => 'dealer_id',
            'foreign' => 'dealer_id'));
        
    }
}
