<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AcivityModuleActivity', 'doctrine');

/**
 * BaseAcivityModuleActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activity_id
 * @property integer $module_id
 * 
 * @method integer               getActivityId()  Returns the current record's "activity_id" value
 * @method integer               getModuleId()    Returns the current record's "module_id" value
 * @method AcivityModuleActivity setActivityId()  Sets the current record's "activity_id" value
 * @method AcivityModuleActivity setModuleId()    Sets the current record's "module_id" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcivityModuleActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acivity_module_activity');
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('module_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}