<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MaterialDownloads', 'doctrine');

/**
 * BaseMaterialDownloads
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $material_id
 * 
 * @method integer           getId()          Returns the current record's "id" value
 * @method integer           getMaterialId()  Returns the current record's "material_id" value
 * @method MaterialDownloads setId()          Sets the current record's "id" value
 * @method MaterialDownloads setMaterialId()  Sets the current record's "material_id" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaterialDownloads extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('material_downloads');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('material_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}