<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Discussion', 'doctrine');

/**
 * BaseDiscussion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property Doctrine_Collection $Messages
 * @property Doctrine_Collection $DealerDiscussions
 * @property Doctrine_Collection $OnlineUsers
 * @property Doctrine_Collection $Models
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method Doctrine_Collection getMessages()          Returns the current record's "Messages" collection
 * @method Doctrine_Collection getDealerDiscussions() Returns the current record's "DealerDiscussions" collection
 * @method Doctrine_Collection getOnlineUsers()       Returns the current record's "OnlineUsers" collection
 * @method Doctrine_Collection getModels()            Returns the current record's "Models" collection
 * @method Discussion          setId()                Sets the current record's "id" value
 * @method Discussion          setMessages()          Sets the current record's "Messages" collection
 * @method Discussion          setDealerDiscussions() Sets the current record's "DealerDiscussions" collection
 * @method Discussion          setOnlineUsers()       Sets the current record's "OnlineUsers" collection
 * @method Discussion          setModels()            Sets the current record's "Models" collection
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiscussion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('discussion');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Message as Messages', array(
             'local' => 'id',
             'foreign' => 'discussion_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('DealerDiscussion as DealerDiscussions', array(
             'local' => 'id',
             'foreign' => 'discussion_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('DiscussionOnline as OnlineUsers', array(
             'local' => 'id',
             'foreign' => 'discussion_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('AgreementModel as Models', array(
             'local' => 'id',
             'foreign' => 'discussion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}