<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AgreementModelValue', 'doctrine');

/**
 * BaseAgreementModelValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $model_id
 * @property integer $field_id
 * @property string $value
 * @property AgreementModel $Model
 * @property AgreementModelField $Field
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method integer             getModelId()  Returns the current record's "model_id" value
 * @method integer             getFieldId()  Returns the current record's "field_id" value
 * @method string              getValue()    Returns the current record's "value" value
 * @method AgreementModel      getModel()    Returns the current record's "Model" value
 * @method AgreementModelField getField()    Returns the current record's "Field" value
 * @method AgreementModelValue setId()       Sets the current record's "id" value
 * @method AgreementModelValue setModelId()  Sets the current record's "model_id" value
 * @method AgreementModelValue setFieldId()  Sets the current record's "field_id" value
 * @method AgreementModelValue setValue()    Sets the current record's "value" value
 * @method AgreementModelValue setModel()    Sets the current record's "Model" value
 * @method AgreementModelValue setField()    Sets the current record's "Field" value
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgreementModelValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agreement_model_value');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('model_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('field_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AgreementModel as Model', array(
             'local' => 'model_id',
             'foreign' => 'id'));

        $this->hasOne('AgreementModelField as Field', array(
             'local' => 'field_id',
             'foreign' => 'id'));
    }
}