<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('City', 'vw_general');

/**
 * BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $region_id
 * @property Region $Region
 * @property Doctrine_Collection $Dealers
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getRegionId()  Returns the current record's "region_id" value
 * @method Region              getRegion()    Returns the current record's "Region" value
 * @method Doctrine_Collection getDealers()   Returns the current record's "Dealers" collection
 * @method City                setName()      Sets the current record's "name" value
 * @method City                setRegionId()  Sets the current record's "region_id" value
 * @method City                setRegion()    Sets the current record's "Region" value
 * @method City                setDealers()   Sets the current record's "Dealers" collection
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cities');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('region_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('orderBy', 'name');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id'));

        $this->hasMany('Dealer as Dealers', array(
             'local' => 'id',
             'foreign' => 'city_id'));
    }
}