all:
  javascripts: 
      - material/list_controller
      - material/window
      - intro/intro.activity.materials.js
      - activity/activity_quarters_data.js
      - activity/activity_material_request_new.js
