generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MaterialWebPreview
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          material_web_preview
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:   
        title: Изменение web-превью
      new:     
        title: Новое web-превью
