generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ActivityStatisticPeriods
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          activity_statistic_periods
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        year: { label: Год }
        quarters: { label: Кварталы }
      list:    ~
      filter:  ~
      form:    ~
      edit:    
        title: Период статистики за "%%year%%"
      new:     
        title: Добавление периода статистики
