all:
  is_secure: false
  credentials: [[ admin, importer, manager, specialist ]]

declineModel:
  credentials: [[ admin, importer, manager ]]
  
acceptModel:
  credentials: [[ admin, importer, manager ]]
  
declineReport:
  credentials: [[ admin, importer, manager ]]
  
acceptReport:
  credentials: [[ admin, importer, manager ]]
  
sendModelToSpecialists:
  credentials: [[ admin, importer, manager ]]
  
sendReportToSpecialists:
  credentials: [[ admin, importer, manager ]]
  
activities:
  is_secure : false
