<?php

/**
 * ActivityExamplesMaterialsCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityExamplesMaterialsCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityExamplesMaterialsCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityExamplesMaterialsCategories');
    }

    public static function getCategoriesList($excluded_cat = 0) {
        $query = self::getInstance()->createQuery()->orderBy('name ASC');

        if ($excluded_cat != 0) {
            $query->andWhere('id != ?', $excluded_cat);
        }

        return $query;
    }

}