<?php

/**
 * ActivityTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityTask');
    }

    public static function getTaskList($activity_id) {
        return self::getInstance()->createQuery()->where('activity_id = ?', $activity_id);
    }
}