<?php

/**
 * ActivityExtendedStatisticSectionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityExtendedStatisticSectionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityExtendedStatisticSectionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityExtendedStatisticSections');
    }
}