<?php

/**
 * ActivityFieldsDateFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityFieldsDateFieldTable extends ActivityFieldsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityFieldsDateFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityFieldsDateField');
    }
}