<?php

/**
 * ActivityTaskResultTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTaskResultTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityTaskResultTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityTaskResult');
    }
}