<?php

/**
 * ActivityCompanyType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ActivityCompanyType extends BaseActivityCompanyType
{
    public function getActivitiesList($activity_id = null) {
        $query = ActivityTable::getInstance()->createQuery()->where('type_company_id = ? and finished = ?', array($this->getId(), false))->orderBy('id DESC');

        if (!is_null($activity_id)) {
            $query->andWhere('id != ?', $activity_id);
        }

        return $query->execute();
    }
}
