<?php

/**
 * ActivityFieldsDateNumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityFieldsNumberFieldTable extends ActivityFieldsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityFieldsDateFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityFieldsNumberField');
    }
}