<?php

/**
 * ActivityInfoFieldsDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityInfoFieldsDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityInfoFieldsDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityInfoFieldsData');
    }
}