<?php

/**
 * ActivityExtendedStatisticStepValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityExtendedStatisticStepValuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityExtendedStatisticStepValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityExtendedStatisticStepValues');
    }
}