<?php

/**
 * ActivityFieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityFieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityFieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityFields');
    }

    public static function getFieldsListByActivityId($activity_id, $header_id) {
        $available_fields = array('' => 'Пустое значение');

        $fields = self::getInstance()->createQuery()->where('activity_id = ? and parent_header_id = ?', array($activity_id, $header_id))->execute();
        foreach ($fields as $field) {
            $available_fields[$field->getId()] = $field->getName();
        }

        return $available_fields;
    }

    public static function getFieldListByFormulaId($formulaId) {
        $formula = ActivityEfficiencyFormulasTable::getInstance()->find($formulaId);

        $activity_statistic = ActivityVideoRecordsStatisticsTable::getInstance()->createQuery()->where('activity_id = ?', $formula->getActivityId())->fetchOne();
        if ($activity_statistic) {
            $activity_statistic_headers = $activity_statistic->getActivityVideoRecordsStatisticsHeaders();

            $result_fields = array();
            foreach ($activity_statistic_headers as $header) {
                $fields = self::getFieldsListByActivityId($formula->getActivityId(), $header->getId());
                $result_fields += $fields;
            }
        }

        return $result_fields;
    }

}
