<?php

/**
 * ActivityStatisticLastUpdatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityStatisticLastUpdatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityStatisticLastUpdatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityStatisticLastUpdates');
    }
}