<?php

/**
 * ActivityStatisticPeriodsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityStatisticPeriodsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityStatisticPeriodsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityStatisticPeriods');
    }
}