<?php

/**
 * ActivityAgreementByUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityAgreementByUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityAgreementByUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityAgreementByUser');
    }
}