<?php

/**
 * ActivityVideoRecordsStatisticsHeadersGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityVideoRecordsStatisticsHeadersGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityVideoRecordsStatisticsHeadersGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityVideoRecordsStatisticsHeadersGroups');
    }
}