<?php

/**
 * ActivityDealerStaticticStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityDealerStaticticStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityDealerStaticticStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityDealerStaticticStatus');
    }
}