<?php

/**
 * ActivityFieldsStringFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityFieldsStringFieldTable extends ActivityFieldsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityFieldsStringFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityFieldsStringField');
    }
}