<?php

/**
 * ActivitiesStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivitiesStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivitiesStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivitiesStatus');
    }
}