<?php

/**
 * ActivityTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ActivityTable
     */
    static function getInstance()
    {
        return Doctrine_Core::getTable('Activity');
    }

    function autoFinish()
    {
        return $this->createQuery()
            ->update()
            ->set('finished', 1)
            ->where('finished=? and (custom_date is null or custom_date=?) and end_date<?', array(
                false, '', D::toDb(time())
            ))->execute();
    }

    function getAcceptStat($year, Dealer $dealer)
    {
        $stat = array(
            1 => array(),
            2 => array(),
            3 => array(),
            4 => array()
        );

        $statsResult = ActivityAcceptStatsTable::getInstance()->createQuery()->where('dealer_id = ? and year = ?', array($dealer->getId(), $year))->fetchOne();
        if ($statsResult) {
            $isLimitRunActivities = array();
            for ($i = 1; $i <= 4; $i++) {
                $qfunc = 'getQ' . $i;

                $qResult = array_filter(explode(':', $statsResult->$qfunc()));
                if (count($qResult) > 0) {
                    $qResult = array_map(function($element) use(&$isLimitRunActivities) {
                        $activity = ActivityTable::getInstance()
                            ->createQuery()
                            ->select('is_limit_run')
                            ->where('id = ?', $element)
                                ->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);

                        if($activity) {
                            if($activity['is_limit_run']) {
                                if(!in_array($element, $isLimitRunActivities)) {
                                    $isLimitRunActivities[] = $element;

                                    return $element;
                                }
                                else {
                                    return null;
                                }
                            }

                            return $element;
                        }
                    }, $qResult);

                    $stat[$i] = array_filter($qResult);
                }
            }
        }

        return $stat;
    }

    function fillAcceptStats($result, &$stat, $dealer, $year)
    {
        if (is_null($stat))
            $stat = array(
                1 => array(),
                2 => array(),
                3 => array(),
                4 => array()
            );

        $minDay = 5;
        $limitActivity = array();
        $incompleteActivities = array();

        foreach ($result as $row) {
            $activity = $row->getActivity();
            $report = $row->getReport();
            if (empty($report) || is_null($report->getId())) {
                if (!in_array($activity->getId(), $incompleteActivities))
                    $incompleteActivities[] = $activity->getId();

                continue;
            }

            if ($report && $report->getStatus() != 'accepted')
                continue;

            $date = $report->getAcceptDate();
            $entry = LogEntryTable::getInstance()
                ->createQuery()
                ->select('created_at')
                ->where('object_id = ?', array($row->getId()))
                ->andWhere('object_type = ? and icon = ? and action = ?', array('agreement_report', 'clip', 'edit'))
                ->orderBy('id DESC')
                ->limit(1)
                ->fetchOne();

            if ($entry)
                $date = $entry->getCreatedAt();

            $nDate = D::calcQuarterData($date);

            $q = D::getQuarter($nDate);
            $tYear = date('Y', $nDate);

            if (!$activity->isActivityStatisticComplete($dealer, $nDate, false, true) || $tYear != $year) {
                continue;
            }

            if (!in_array($activity->getId(), $stat[$q])) {
                if (count($stat[$q]) < 4) {
                    if ($activity->isLimitRun()) {
                        if (!in_array($activity->getId(), $limitActivity)) {
                            $limitActivity[] = $activity->getId();
                            $stat[$q][] = $activity->getId();
                        } else
                            continue;
                    } else {
                        $stat[$q][] = $activity->getId();
                    }
                }
            }
        }

        return $stat;
    }

    /**
     * @param $result
     * @param $stat
     * @param $dealer
     * @param $year
     * @param null $mandatory_activities
     * @return array
     */
    static function fillAcceptStatsArray($result, &$stat, $dealer, $year, $mandatory_activities = null)
    {
        if (is_null($stat))
            $stat = array(
                1 => array(),
                2 => array(),
                3 => array(),
                4 => array()
            );

        $limitActivity = array();
        $incompleteActivities = array();

        $activities = array();
        $activityStatsQ = array();

        foreach ($result as $row) {
            if (isset($row['report_id']) && is_null($row['report_id'])) {
                if (!in_array($row['activity_id'], $incompleteActivities))
                    $incompleteActivities[] = $row['activity_id'];

                continue;
            }

            $date = $row['rAcceptDate'];
            if (isset($row['logCreatedAt']) && !empty($row['logCreatedAt'])) {
                $date = $row['logCreatedAt'];
            }

            $nDate = D::calcQuarterData($date);
            $q = D::getQuarter($nDate);
            $tYear = date('Y', $nDate);

            //Делаем проверку на обязательную активность по году и кварталу
            if ($q > 1) {
                if (!is_null($mandatory_activities) &&
                    isset($mandatory_activities[$tYear]) &&
                    isset($mandatory_activities[$tYear][$q]) &&
                    !in_array($row['activity_id'], $mandatory_activities[$tYear][$q]))
                {
                    continue;
                }
            }

            if (!array_key_exists($row['activity_id'], $activities)) {
                $activities[$row['activity_id']] = ActivityTable::getInstance()->createQuery()->where('id = ?', $row['activity_id'])->fetchOne();
            }

            /** @var Activity $activity */
            $activity = $activities[$row['activity_id']];
            if (!$activity->isActivityStatisticComplete($dealer, $nDate, false, $year, $q) || $tYear != $year) {
                continue;
            }

            //Mandatory activity by quarters
            if ($activity->getMandatoryActivity() && $activity->hasMandatoryStatus()) {
                $mandatory_activity_q = $activity->getMandatoryQuartersList(true, $tYear);

                //Только для кварталов которые больше 1-го
                if ($q > 1) {
                    //If current quarter not in mandatory quarters list, do not check activity as complete
                    if (!in_array($q, $mandatory_activity_q)) {
                        continue;
                    }
                }
            }

            $activityStatsQ[$q][] = array('activity_id' => $activity->getId(), 'is_limit' => $activity->isLimitRun());
        }

        /*Checking limit run activity*/
        ksort($activityStatsQ);
        foreach($activityStatsQ as $q => $datas)
        {
            foreach($datas as $data)
            {
                if (!in_array($data['activity_id'], $stat[$q]) && count($stat[$q]) < 4) {
                    if ($data['is_limit']) {
                        if (!in_array($data['activity_id'], $limitActivity)) {
                            $limitActivity[] = $data['activity_id'];
                            $stat[$q][] = $data['activity_id'];

                        } else {
                            continue;
                        }
                    } else {
                        $stat[$q][] = $data['activity_id'];
                    }
                }
            }
        }

        return $stat;
    }

    /**
     * @param $user
     * @param $query
     */
    static function checkActivity($user, &$query, $company_type_id, $filters = null, $year = null)
    {
        /*Service dialogs*/
        $dealer = $user->getAuthUser()->getDealerUsers()->getFirst();
        if ($dealer) {
            $servicesData = DealersServiceDataTable::getInstance()->createQuery()
                ->where('dealer_id = ? and status = ?', array($dealer->getDealerId(), 'accepted'))->execute();

            $activities = array();
            foreach ($servicesData as $data) {
                $activities[] = $data->getDialog()->getActivityId();
            }

            //self::makeQuery($query, array_filter($activities), $company_type_id, $filters);
            self::makePartialQuery($query, array_filter($activities), $company_type_id, $filters);
        }
    }

    /**
     * @param $query
     * @param $ids
     * @param $company_type_id
     * @param $filters
     */
    static function makeQuery(&$query, $ids, $company_type_id, $filters)
    {
        $query_str = '(a.hide = ? and type_company_id = ?';
        $query_arr = array
        (
            true,
            $company_type_id,
        );

        $allow_services_activities_ids = true;
        if (isset($filters['finished']) && $filters['finished']) {
            $allow_services_activities_ids = false;
        }

        if (!empty($ids) && $allow_services_activities_ids) {
            $query_str .= ' and (a.id in ?)';
            $query_arr[] = $ids;
        }

        $query_sub_q = array();
        if ($filters['filter_by_owned'] == 1) {
            $query_sub_q[] = 'own_activity = ?';
            $query_arr[] = 1;
        }

        if ($filters['filter_by_required'] == 1) {
            $query_sub_q[] = 'required_activity = ?';
            $query_arr[] = 1;
        }

        if (count($query_sub_q) > 0) {
            $query_str .= ' and (';
            $query_str .= implode(' or ', $query_sub_q);
            $query_str .= ')';
        }

        if (!is_null($filters)) {
            if ($filters['year'] && !D::isSpecialFirstQuarter($filters['request'])) {
                $query_str .= ' and (year(a.start_date) <= ? and year(a.end_date) >= ?)';
                $query_arr[] = $filters['year'];
                $query_arr[] = $filters['year'];

                $query_str .= ' and (a.finished = ? or allow_extended_statistic = ?)';
                if (isset($filters['finished']) && $filters['finished']) {
                    $query_arr[] = true;
                } else {
                    $query_arr[] = false;
                }
                $query_arr[] = true;
            } else {
                $query_str .= ' and a.finished = ?';
                if (isset($filters['finished']) && $filters['finished']) {
                    $query_arr[] = true;
                    $query->andWhere('a.finished = ?', true);
                } else {
                    $query_arr[] = false;
                    $query->andWhere('a.finished = ?', false);
                }
            }
        }
        $query_str .= ')';

        $query->orWhere(
            $query_str,
            $query_arr
        );
    }

    static function makePartialQuery(&$query, $ids, $company_type_id, $filters)
    {
        $query_str = '(type_company_id = ?';
        $query_arr = array
        (
            $company_type_id,
        );

        $allow_services_activities_ids = true;
        if (isset($filters['finished']) && $filters['finished']) {
            $allow_services_activities_ids = false;
        }

        if (!empty($ids) && $allow_services_activities_ids) {
            $query_str .= ' and (a.id in ?)';
            $query_arr[] = $ids;
        }

        $query_sub_q = array();
        if ($filters['filter_by_owned'] == 1) {
            $query_sub_q[] = 'a.own_activity = ?';
            $query_arr[] = 1;
        }

        if ($filters['filter_by_required'] == 1) {
            $query_sub_q[] = 'a.required_activity = ?';
            $query_arr[] = 1;
        }

        if (count($query_sub_q) > 0) {
            $query_str .= ' and (';
            $query_str .= implode(' or ', $query_sub_q);
            $query_str .= ')';
        }

        if (!is_null($filters)) {
            if ($filters['year'] && !D::isSpecialFirstQuarter($filters['request'])) {
                $query_str .= ' and (year(a.start_date) <= ? and year(a.end_date) >= ?)';
                $query_arr[] = $filters['year'];
                $query_arr[] = $filters['year'];

                $query_str .= ' and (a.finished = ? or a.allow_extended_statistic = ?)';
                if (isset($filters['finished']) && $filters['finished']) {
                    $query_arr[] = true;
                } else {
                    $query_arr[] = false;
                }
                $query_arr[] = true;
            } else {
                $query_str .= ' and a.finished = ?';
                if (isset($filters['finished']) && $filters['finished']) {
                    $query_arr[] = true;
                    $query->andWhere('a.finished = ?', true);
                } else {
                    $query_arr[] = false;
                    $query->andWhere('a.finished = ?', false);
                }
            }
        }
        $query_str .= ')';

        $query->orWhere(
            $query_str,
            $query_arr
        );
    }

    public static function getActivitesList() {
        return self::getInstance()->createQuery()->orderBy('id DESC');
    }
}
