<?php

/**
 * ActivityMaterialsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityMaterialsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityMaterialsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityMaterials');
    }
}