<?php

/**
 * ActivityVideoRecordsStatistics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ActivityVideoRecordsStatistics extends BaseActivityVideoRecordsStatistics
{
    const FILTER_NAMESPACE = 'activity_video_statistics';

    public function getHeadersList() {
        return ActivityVideoRecordsStatisticsHeadersTable::getInstance()->createQuery()->where('parent_id = ?', $this->getId())->orderBy('position ASC')->execute();
    }

    public function getGroupsList() {
        return ActivityVideoRecordsStatisticsHeadersGroupsTable::getInstance()->createQuery()->where('parent_id = ?', $this->getId())->execute();
    }

    public function getFieldsList() {
        return arraY();
    }

    public function getActivity() {
        return ActivityTable::getInstance()->find($this->getActivityId());
    }

    /**
     * Получаем краткое описание к статисике
     * @return string
     */
    public function getStatisticDescription() {
        //Получаем описание с самой статисики, если нет то смотрим в заголовках статистики
        $description = $this->getDescription();
        if (!empty($description)) {
            return $description;
        }

        $descriptionItem = ActivityVideoRecordsStatisticsHeadersTable::getInstance()->createQuery()->where('parent_id = ? and position = ?', array($this->getId(), 0))->fetchOne();
        if ($descriptionItem) {
            return $descriptionItem->getDescription();
        }

        return '';
    }
}
