<?php

/**
 * ActivitiesStatusByUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivitiesStatusByUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivitiesStatusByUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivitiesStatusByUsers');
    }

    public static function checkActivityStatus($activity_id, $dealer_id, $year, $quarter = null) {
        if (is_null($year)) {
            $year = D::getYear(date('Y-m-d'));
        }

        $query = self::getInstance()->createQuery()->where('activity_id = ? and dealer_id = ? and by_year = ?', array($activity_id, $dealer_id, $year));
        if (!is_null($quarter)) {
            $query->andWhere('by_quarter = ?', $quarter);
        }

        return $query->count() > 0 ? true : false;
    }

    public static function getCompletedActivitiesList($year = null, $quarter = null) {
        if (is_null($year)) {
            $year = D::getYear(date('Y-m-d'));
        }

        $items = array();

        $query = self::getInstance()->createQuery()->where('by_year = ?', array($year));
        if (!is_null($quarter)) {
            $query->andWhere('by_quarter = ?', $quarter);
        }

        $result = $query->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
        foreach ($result as $item) {
            $items[$item['activity_id']][] = $item;
        }

        return $items;
    }
}
