<?php

/**
 * AgreementModelValueTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelValue');
    }

    /**
     * Get period value from model
     * @param $model
     * @return array|bool|null|string
     */
    public static function getPeriodValueFromModel($model)
    {
        $values = $model['Values'];

        //Проверка периода в новых категориях
        if ($model['model_category_id'] != 0 && !empty($model['period'])) {
            $value = $model['period'];
        }

        if (!empty($value)) {
            return self::getValueDate($value);
        }

        foreach ($values as $key => $value_data) {
            $value = '';

            $field = AgreementModelFieldTable::getInstance()->find($value_data['field_id']);
            if ($field && $field->isPeriodField()) {
                $value = $value_data['value'];
            }

            if (empty($value)) {
                return false;
            }

            return self::getValueDate($value);
        }

        return false;
    }

    /**
     * @param $value
     * @return array|null|string
     */
    private static function getValueDate($value) {
        $value = explode('-', $value);
        if (!empty($value[1])) {
            $value = $value[1];

            $value = explode('.', $value);
            $dt = DateTime::createFromFormat('Y', '20'.$value[2]);

            if ($dt) {
                $value = sprintf('%s-%s-%s', $value[0], $value[1], $dt->format('Y'));
            } else {
                $value = '';
            }
        } else {
            return false;
        }

        return $value;
    }
}
