<?php

/**
 * AgreementModelCategoriesTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelCategoriesTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelCategoriesTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelCategoriesTypes');
    }
}