<?php

/**
 * AgreementModelPeriodFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelExtPeriodFieldTable extends AgreementModelFieldTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelPeriodFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelExtPeriodField');
    }
}