<?php

/**
 * AgreementModelsBlockInform
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AgreementModelsBlockInform extends BaseAgreementModelsBlockInform
{
    const INFORM_STATUS_LEFT_10 = 'left_10';
    const INFORM_STATUS_LEFT_2 = 'left_2';
    const INFORM_STATUS_BLOCKED = 'blocked';
}
