<?php

/**
 * AgreementModelDatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelDatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelDatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelDates');
    }
}