<?php

/**
 * AgreementModelSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelSettings');
    }
}