<?php

/**
 * AgreementModelListFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelListFieldTable extends AgreementModelFieldTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelListFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelListField');
    }
}