<?php

/**
 * AgreementModelReportFilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelReportFilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelReportFilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelReportFiles');
    }

    public static function unlinkModelsFiles($modelId) {
        $files_list = self::getInstance()->createQuery()->select('file')->where('object_id = ?', $modelId)->execute(array(), Doctrine_Core::HYDRATE_ARRAY);

        foreach ($files_list as $file_item) {
            $file_link = sfConfig::get('sf_upload_dir') . '/' . AgreementModel::MODEL_FILE_PATH . '/' . $file_item['file'];
            if (file_exists($file_link)) {
                unlink($file_link);
            }
        }
    }

    /**
     * Get uploaded files list | count by object (model or report) and uploaded files types
     * @param $object_id
     * @param $objectType
     * @param $fileType
     * @param bool $count
     * @param bool $as_array
     * @return mixed
     */
    public static function getUploadedFilesListBy($object_id, $objectType, $fileType, $count = false, $as_array = false, $upload_activity_id = 0)
    {
        $query = self::getInstance()
            ->createQuery()
            ->where('object_type = ? and file_type = ? and object_id = ?',
                array
                (
                    //sfContext::getInstance()->getUser()->getAuthUser()->getId(),
                    $objectType,
                    $fileType,
                    $object_id
                )
            );

        if ($upload_activity_id != 0) {
            //$query->andWhere('activity_id = ?', $upload_activity_id);
        }

        if ($count) {
            return $query->count();
        }

        return $as_array ? $query->execute(array(), Doctrine_Core::HYDRATE_ARRAY) : $query->execute();
    }

}
