<?php

/**
 * AgreementModelBlankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelBlankTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return AgreementModelBlankTable
   */
  static function getInstance()
  {
    return Doctrine_Core::getTable('AgreementModelBlank');
  }
  
  function hasActivityBlanks(Activity $activity)
  {
    return $this->createQuery()
           ->where('activity_id=?', $activity->getId())
           ->count() > 0;
  }
  
  function didAllBlanks(Activity $activity, Dealer $dealer)
  {
    $query = AgreementModelBlankTable::getInstance()
             ->createQuery('b')
             ->leftJoin('b.Models m WITH m.dealer_id=?', $dealer->getId())
             ->leftJoin('m.Report r WITH r.status=?', 'accepted')
             ->where('b.activity_id=? and r.id is null', $activity->getId());
    
    return $query->count() == 0;
  }
}