<?php

/**
 * AgreementModelsBlockInformTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementModelsBlockInformTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementModelsBlockInformTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementModelsBlockInform');
    }
}