<?php

/**
 * CalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarTable extends Doctrine_Table
{
    static private $_dates = array();

    /**
     * Returns an instance of this class.
     *
     * @return object CalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Calendar');
    }

    public static function getCalendarDates() {
        if (empty(self::$_dates)) {
            $items = CalendarTable::getInstance()->createQuery()
                ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);

            foreach ($items as $item) {
                self::$_dates[$item['start_date']] = $item;
            }
        }

        return self::$_dates;
    }
}