<?php

/**
 * DealersTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealersTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealersTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealersTypes');
    }
}