<?php

/**
 * DealerActivitiesStatsManagersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealerActivitiesStatsManagersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealerActivitiesStatsManagersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealerActivitiesStatsManagers');
    }

    public static function getRawTableName() {
        return "dealer_activities_stats_managers";
    }
}