<?php

/**
 * DealerActivitiesStatsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealerActivitiesStatsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealerActivitiesStatsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealerActivitiesStats');
    }

    public static function getRawTableName() {
        return "dealer_activities_stats";
    }
}