<?php

/**
 * DealersBudgetsFilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealersBudgetsFilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealersBudgetsFilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealersBudgetsFiles');
    }
}