<?php

/**
 * DealerWorkStatisticModelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealerWorkStatisticModelsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealerWorkStatisticModelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealerWorkStatisticModels');
    }
}