<?php

/**
 * DealersControlPointByTermsOfLoadingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealersControlPointByTermsOfLoadingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealersControlPointByTermsOfLoadingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealersControlPointByTermsOfLoading');
    }
}