<?php

/**
 * DealerUserPkwNfzTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealerUserPkwNfzTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealerUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealerUserPkwNfz');
    }
}