<?php

/**
 * FaqsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Faqs');
    }
}