<?php

/**
 * LogEntry
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LogEntry extends BaseLogEntry
{
    const LOG_ACTION_DEALER_MODEL_BLOCK_INFORM = 'dealer_model_block_inform';

    /**
     * Creates a private copy of the entry
     *
     * @param User $user
     * @return LogEntry a copy
     */
    function createPrivateCopy(User $user)
    {
        $copy = $this->copy();
        $copy->setPrivateUser($user);
        $copy->save();

        if ($user->getId() == $this->getUserId())
            LogEntryReadTable::getInstance()->addRead($this->getUser(), $copy);

        return $copy;
    }
}