<?php

/**
 * LogLastReadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogLastReadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogLastReadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogLastRead');
    }
}