<?php

/**
 * MailMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailMessage');
    }

    public function getSpooledMessages()
    {
        return $this->createQuery('m')
                        ->orderBy('m.priority');
    }

    /**
     * Отправка писем по статусу согласования (менеджер / специалист)
     * @param AgreementModel $model
     */
    public static function sendMails(AgreementModel $model) {
        //Если менеджер / специалист согласовали или отклонили заявку отправляем все письма в ожидании
        if (($model->getManagerStatus() == 'declined' && $model->getDesignerStatus() == 'declined') ||
            ($model->getManagerStatus() == 'accepted' && $model->getDesignerStatus() == 'accepted'))
        {
            //Активируем отправку писем
            $mails_list = self::getInstance()->createQuery()->where('model_id = ? and can_send = ?', array($model->getId(), false))->execute();
            foreach ($mails_list as $mail) {
                $mail->setCanSend(true);
                $mail->save();
            }
        }
        //Если менеджер согласовал и специалист нет, удаляем все письма от менеджера, письма от специалиста отправляем
        else if ($model->getManagerStatus() == 'accepted' && $model->getDesignerStatus() != 'accepted') {
            //Удалем письма
            self::getInstance()->createQuery()->where('model_id = ? and msg_type = ?', array($model->getId(), Message::MSG_TYPE_MANAGER))->delete()->execute();

            //Активируем отправку писем
            $mails_list = self::getInstance()->createQuery()->where('model_id = ? and can_send = ?', array($model->getId(), false))->execute();
            foreach ($mails_list as $mail) {
                $mail->setCanSend(true);
                $mail->save();
            }
        }
        //Если менеджер не согласовал а специалист да, отправляем все письма от менеджера, письма от специалиста удаляем
        else if ($model->getManagerStatus() != 'accepted' && $model->getDesignerStatus() == 'accepted') {
            //Удалем письма
            self::getInstance()->createQuery()->where('model_id = ? and msg_type = ?', array($model->getId(), Message::MSG_TYPE_SPECIALIST))->delete()->execute();

            //Активируем отправку писем
            $mails_list = self::getInstance()->createQuery()->where('model_id = ? and can_send = ?', array($model->getId(), false))->execute();
            foreach ($mails_list as $mail) {
                $mail->setCanSend(true);
                $mail->save();
            }
        }
    }
}
