<?php

/**
 * MainMenuItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MainMenuItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MainMenuItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MainMenuItems');
    }
}