<?php

/**
 * MandatoryActivityQuartersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MandatoryActivityQuartersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MandatoryActivityQuartersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MandatoryActivityQuarters');
    }
}