<?php

/**
 * MaterialDownloadsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialDownloadsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialDownloadsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialDownloads');
    }
}