<?php

/**
 * MaterialSource
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MaterialSource extends BaseMaterialSource
{
    const FILE_PATH = 'materials/source';
    const SERVER_FILES_PATH = 'uploads_raw/materials/source';

    function setUp()
    {
        parent::setUp();

        $this->addListener(new UploadHelper('file', self::FILE_PATH));
    }

    function setFromServerFile($file)
    {
        $src = sfConfig::get('sf_upload_dir') . '/' . self::SERVER_FILES_PATH . '/' . $file;
        $name_generator = new UniqueFileNameGenerator(sfConfig::get('sf_upload_dir') . '/' . self::FILE_PATH);
        $dst = $name_generator->getPath() . '/' . $name_generator->generate($file);

        rename($src, $dst);

        $this->setFile(basename($dst));

    }

    /**
     * Returns a file name helper for model
     *
     * @return FileNameHelper
     */
    function getFileNameHelper()
    {
        return new FileNameHelper(
            sfConfig::get('sf_upload_dir') . '/' . self::FILE_PATH . '/' . $this->getFile(),
            array('pdf', 'id', 'jpg', 'indd', 'eps', 'tiff', 'mp3', 'psd', 'tif', 'zip', 'doc', 'fla', 'swf', 'doc', 'docx', 'rar', 'cdr')
        );
    }

}
