<?php

/**
 * MaterialDownloads
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MaterialDownloads extends BaseMaterialDownloads
{
    public function getActivitiesList() {
        $activities = array();

        $material = MaterialTable::getInstance()->find($this->getMaterialId());
        if ($material) {
            $items = $material->getMaterialActivities();
            foreach ($items as $item) {
                if ($activity = ActivityTable::getInstance()->find($item->getActivityId())) {
                    $activities[] = $activity;
                }
            }
        }

        return $activities;
    }
}
