<?php

/**
 * MaterialSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialSourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialSource');
    }
}