<?php

/**
 * RealTotalBudgetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RealTotalBudgetTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return RealTotalBudgetTable
   */
  static function getInstance()
  {
    return Doctrine_Core::getTable('RealTotalBudget');
  }
  
  function recalculate(Dealer $dealer, $year)
  {
    $this->createQuery()
         ->delete()
         ->where('dealer_id=? and year=?', array($dealer->getId(), $year))
         ->execute();
    
//    Doctrine_Manager::connection()->flush();
    
    $calculator = new RealBudgetCalculator($dealer, $year);
    foreach($calculator->calculate() as $quarter => $sum)
    {
      if($sum)
      {
        $total = new RealTotalBudget();
        $total->setArray(array(
          'dealer_id' => $dealer->getId(),
          'year' => $year,
          'quarter' => $quarter,
          'sum' => $sum
        ));
        $total->save();
      }
    }
  }
}