<?php

/**
 * TempFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TempFile extends BaseTempFile
{
  const FILE_PATH = 'temp/file';
  
  function setUp()
  {
    parent::setUp();
    
    $this->addListener(new UploadHelper('file', self::FILE_PATH));
  }
  
  function apply($new_path)
  {
    rename(sfConfig::get('sf_upload_dir').'/'.self::FILE_PATH.'/'.$this->getFile(), $new_path);
    $this->delete();
  }
}