<?php

/**
 * UpdateActivityStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UpdateActivityStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return UpdateActivityStatusTable
     */
    static function getInstance()
    {
      return Doctrine_Core::getTable('UpdateActivityStatus');
    }
    
    function shedule(Activity $activity, Dealer $dealer)
    {
      $update = $this->createQuery()
                     ->where('activity_id=? and dealer_id=?', array($activity->getId(), $dealer->getId()))
                     ->fetchOne();
      
      if(!$update)
      {
        $update = new UpdateActivityStatus();
        $update->setActivity($activity);
        $update->setDealer($dealer);
        $update->save();
      }
    }
}