<?php

/**
 * UserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Servicepool2.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserGroup extends BaseUserGroup
{
  function isSpecialist()
  {
    return !!RoleTable::getInstance()
           ->createQuery('r')
           ->innerJoin('r.GroupRoles gr WITH gr.group_id=?', $this->getId())
           ->where('r.role=?', 'specialist')
           ->fetchOne();
  }
  
  /**
   * Returns active users
   * 
   * @return Doctrine_Collection
   */
  function getActiveUsers()
  {
    return UserTable::getInstance()
           ->createQuery()
           ->where('active=? and group_id=?', array(true, $this->getId()))
           ->execute();
  }
}