<?php

/**
 * UsersDepartmentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersDepartmentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersDepartmentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersDepartments');
    }

    /**
     * @param int $parent_id
     * @return mixed
     */
    public static function getDepartments($parent_id = 0) {
        if ($parent_id != 0) {
            return self::getInstance()->createQuery()->where('parent_id = ?', $parent_id)->orderBy('id ASC');
        }

        return self::getInstance()->createQuery()->where('parent_id = 0')->orderBy('id ASC');
    }

}
