<?php

/**
 * VariableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VariableTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return VariableTable
   */
  static function getInstance()
  {
      return Doctrine_Core::getTable('Variable');
  }
  
  function getValue($name, $default = false)
  {
    $var = $this->findOneByName($name);
    return $var ? $var->getValue() : $default;
  }
  
  function setValue($name, $value)
  {
    $var = $this->findOneByName($name);
    
    if(!$var)
    {
      $var = new Variable();
      $var->setName($name);
    }
    
    $var->setValue($value);
    
    $var->save();
  }
}