generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ActivityVideoRecordsStatisticsHeadersGroups
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          activity_video_records_statistics_headers_groups
    with_doctrine_route:   true
    actions_base_class:    sfActions
    with_wildcard_routes:  true

    config:
      actions: ~
      fields:  
        header: { label: Название }
        parent_header_id: { label: Привязка к заголовку }
        allow_user_to_add: { label: Разрешить добавление полей пользователем }
      list:
        title: Список групп полей
        display: [ id, header, allow_user_to_add ]
        max_per_page: 25
        actions: {}
      filter:
       class: false
      form:    ~
      edit:    
        title: Параметры "%%header%%"
      new:     
        title: Новая группа


