all:
  stylesheets: [manager]

dealersSuccess:
  has_layout: false

activitiesStatusSuccess:
  stylesheets: [activities_status_table, plugins/animate.min.css]
  javascripts: [filter/filter, table-highlighter/table-highlighter, table-header-fixer/table-header-fixer]