all:
  stylesheets: [manager, fancybox/jquery.fancybox.min.css]
  javascripts:
    - intro/intro.activity.info.js
    - activity/activity_quarters_data.js
    - activity/activity_video_record_statistic.js
    - activity/activity_extended_statistic.js
    - activity/statictic/activity_simple_statistic.js
    - activity/efficiency/activity_efficiency_graph_arrow.js
    - libs/jquery.animateNumber.min.js
    - activity/dealer_information_block.js
    - activity/special_agreement_concept_bind_target_and_statistic.js
    - plugins/tinymce/tinymce.min.js
    - fancybox/jquery.fancybox.min.js

statisticInfoSuccess:
  stylesheets: [activities_status_table]
  javascripts: [filter/filter, table-highlighter/table-highlighter, table-header-fixer/table-header-fixer]

efficiencyInfoSuccess:
  stylesheets: [activities_status_table]
  javascripts: [filter/filter, table-highlighter/table-highlighter, table-header-fixer/table-header-fixer]

dealersWorkStatisticsSuccess:
  stylesheets: [ toastr/toastr.css, activities_status_table.css, multiselect/jquery.multiselect.css, plugins/sweetalert/sweetalert.css ]
  javascripts: [ plugins/toastr/toastr.js, messages/messages.js, multiselect/jquery.multiselect.js, dealers/consolidated_information_dealer, plugins/sweetalert/sweetalert.min.js ]

extendedStatisticByStepsSuccess:
  stylesheets: [manager]
  javascripts:
    - activity/activity_extended_steps_statistic.js
