all:
  stylesheets: [manager, jquery.multiselect.css, plugins/sweetalert/sweetalert.css ]
  javascripts: 
    - intro/intro.activity.approvement.js
    - activity/activity_quarters_data.js
    - libs/jquery.multiselect.js
    - plugins/sweetalert/sweetalert.min.js
