generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ActivityInfo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          activity_info
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        icon: { label: Иконка }
        name: { label: Название }
        text: { label: Текст }
        sort: { label: Сортировка }
      list:    ~
      filter:  ~
      form:    ~
      edit:   
        title: %%name%%
      new:     
        title: Новая информация
