<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddLegalPerson extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('legal_person', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'legal_address' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'inn' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'kpp' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'okpo' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'transactional_account' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'correspondent_account' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'bik' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'bank_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createForeignKey('dealer', 'dealer_company_id_legal_person_id', array(
             'name' => 'dealer_company_id_legal_person_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'legal_person',
             ));
        $this->addIndex('dealer', 'dealer_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dealer', 'dealer_company_id_legal_person_id');
        $this->removeIndex('dealer', 'dealer_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->dropTable('legal_person');
    }
}