<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddAgreementModelTypeTables extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('agreement_model_field', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'model_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'identifier' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'string',
              1 => 'date',
              2 => 'select',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'sort' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '8',
             ),
             'list' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('agreement_model_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '255',
             ),
             'identifier' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '255',
             ),
             'report_field_description' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createForeignKey('agreement_model_field', 'amai', array(
             'name' => 'amai',
             'local' => 'model_type_id',
             'foreign' => 'id',
             'foreignTable' => 'agreement_model_type',
             ));
        $this->addIndex('agreement_model_field', 'agreement_model_field_model_type_id', array(
             'fields' => 
             array(
              0 => 'model_type_id',
             ),
             ));
        $this->addIndex('agreement_model_field', 'agreement_model_field_type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('agreement_model_field', 'amai');
        $this->removeIndex('agreement_model_field', 'agreement_model_field_model_type_id', array(
             'fields' => 
             array(
              0 => 'model_type_id',
             ),
             ));
        $this->removeIndex('agreement_model_field', 'agreement_model_field_type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->dropTable('agreement_model_field');
        $this->dropTable('agreement_model_type');
    }
}