<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RemoveRelationBetweenModelAndDealerUser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('agreement_model', 'agreement_model_dealer_user_id_dealer_user_id');
        $this->removeColumn('agreement_model', 'dealer_user_id');
    }

    public function down()
    {
        $this->addColumn('agreement_model', 'dealer_user_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->createForeignKey('agreement_model', 'agreement_model_dealer_user_id_dealer_user_id', array(
             'name' => 'agreement_model_dealer_user_id_dealer_user_id',
             'local' => 'dealer_user_id',
             'foreign' => 'id',
             'foreignTable' => 'dealer_user',
             ));
    }
}