<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class changeLengthOfEntryLogDescriptoion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('log', 'description', 'clob', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('log', 'description', 'string', '255', array(
             'notnull' => '1',
             ));
    }
}