<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddAgreementConceptTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('agreement_concept', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'file' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
              3 => 'not_sent',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'activity_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'dealer_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'agreement_comments' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'agreement_comments_file' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createForeignKey('agreement_concept', 'agreement_concept_activity_id_activity_id', array(
             'name' => 'agreement_concept_activity_id_activity_id',
             'local' => 'activity_id',
             'foreign' => 'id',
             'foreignTable' => 'activity',
             ));
        $this->createForeignKey('agreement_concept', 'agreement_concept_dealer_id_dealers_id', array(
             'name' => 'agreement_concept_dealer_id_dealers_id',
             'local' => 'dealer_id',
             'foreign' => 'id',
             'foreignTable' => 'dealers',
             ));
        $this->addIndex('agreement_concept', 'agreement_concept_activity_id', array(
             'fields' => 
             array(
              0 => 'activity_id',
             ),
             ));
        $this->addIndex('agreement_concept', 'agreement_concept_dealer_id', array(
             'fields' => 
             array(
              0 => 'dealer_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('agreement_concept', 'agreement_concept_activity_id_activity_id');
        $this->dropForeignKey('agreement_concept', 'agreement_concept_dealer_id_dealers_id');
        $this->removeIndex('agreement_concept', 'agreement_concept_activity_id', array(
             'fields' => 
             array(
              0 => 'activity_id',
             ),
             ));
        $this->removeIndex('agreement_concept', 'agreement_concept_dealer_id', array(
             'fields' => 
             array(
              0 => 'dealer_id',
             ),
             ));
        $this->dropTable('agreement_concept');
    }
}