<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddDiscussionLastRead extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('discussion_last_read', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'message_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
         $this->createForeignKey('discussion_last_read', 'discussion_last_read_message_id_message_id', array(
             'name' => 'discussion_last_read_message_id_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'message',
             ));
        $this->createForeignKey('discussion_last_read', 'discussion_last_read_user_id_user_id', array(
             'name' => 'discussion_last_read_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->addIndex('discussion_last_read', 'discussion_last_read_message_id', array(
             'fields' => 
             array(
              0 => 'message_id',
             ),
             ));
        $this->addIndex('discussion_last_read', 'discussion_last_read_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
   }

    public function down()
    {
        $this->dropForeignKey('discussion_last_read', 'discussion_last_read_message_id_message_id');
        $this->dropForeignKey('discussion_last_read', 'discussion_last_read_user_id_user_id');
        $this->removeIndex('discussion_last_read', 'discussion_last_read_message_id', array(
             'fields' => 
             array(
              0 => 'message_id',
             ),
             ));
        $this->removeIndex('discussion_last_read', 'discussion_last_read_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
       $this->dropTable('discussion_last_read');
    }
}