<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTempFiles extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('temp_file', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'file' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createForeignKey('temp_file', 'temp_file_user_id_user_id', array(
             'name' => 'temp_file_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->addIndex('temp_file', 'temp_file_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
   }

    public function down()
    {
      $this->dropForeignKey('temp_file', 'temp_file_user_id_user_id');
      $this->removeIndex('temp_file', 'temp_file_user_id', array(
           'fields' => 
           array(
            0 => 'user_id',
           ),
           ));
      $this->dropTable('temp_file');
    }
}