<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddFulltextIndexForMossages extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('message', 'content', array(
             'fields' => 
             array(
              0 => 'text',
             ),
             'type' => 'fulltext',
             ));
    }

    public function down()
    {
        $this->removeIndex('message', 'content', array(
             'fields' => 
             array(
              0 => 'text',
             ),
             'type' => 'fulltext',
             ));
    }
}