<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIndexForModelTypeName extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('agreement_model_type', 'name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('agreement_model_type', 'name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
    }
}