<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addTitleAndIconToLog extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('log', 'title', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('log', 'icon', 'string', '255', array(
             'notnull' => '',
             ));
        $this->changeColumn('log', 'description', 'clob', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('log', 'title');
        $this->removeColumn('log', 'icon');
    }
}