<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddVariableTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('variable', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'value' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
              'name' => 
              array(
              'fields' => 
              array(
               0 => 'name',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('variable');
    }
}