<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIndexByCreateDateOfLogEntry extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('log', 'created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('log', 'created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
    }
}