<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddMessageIdToLogEntry extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('log', 'message_id', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->createForeignKey('log', 'log_message_id_message_id', array(
             'name' => 'log_message_id_message_id',
             'local' => 'message_id',
             'foreign' => 'id',
             'foreignTable' => 'message',
             ));
        $this->addIndex('log', 'log_message_id', array(
             'fields' => 
             array(
              0 => 'message_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('log', 'log_message_id_message_id');
        $this->removeIndex('log', 'log_message_id', array(
             'fields' => 
             array(
              0 => 'message_id',
             ),
             ));
        $this->removeColumn('log', 'message_id');
    }
}