<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUniqueIndexForLogLastRead extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('log_last_read', 'user_id', 'integer', '8', array(
             'unique' => '1',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('log_last_read', 'user_id', 'integer', '8', array(
             'unique' => '0',
             'notnull' => '1',
             ));
    }
}