<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReplacedEntryIdWithDateForLastLogRead extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('log_last_read', 'entry_id');
        $this->addColumn('log_last_read', 'last_read', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('log_last_read', 'entry_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->removeColumn('log_last_read', 'last_read');
    }
}