<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUniqueIndexForLogEntryRead extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('log_entry_read', 'user_entry', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'entry_id',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('log_entry_read', 'user_entry', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'entry_id',
             ),
             'type' => 'unique',
             ));
    }
}