<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddRelationBetweenLogEntryAndReads extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('log_entry_read', 'log_entry_read_entry_id_log_id', array(
             'name' => 'log_entry_read_entry_id_log_id',
             'local' => 'entry_id',
             'foreign' => 'id',
             'foreignTable' => 'log',
             ));
        $this->addIndex('log_entry_read', 'log_entry_read_entry_id', array(
             'fields' => 
             array(
              0 => 'entry_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('log_entry_read', 'log_entry_read_entry_id_log_id');
        $this->removeIndex('log_entry_read', 'log_entry_read_entry_id', array(
             'fields' => 
             array(
              0 => 'entry_id',
             ),
             ));
    }
}