<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddMaterialUrlForActivity extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('activity', 'materials_url', 'string', '255', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('activity', 'materials_url');
    }
}