<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddActivityTaskResult extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('activity_task_result', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'dealer_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'task_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'done' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '1',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
              'dealer_task' => 
              array(
              'fields' => 
              array(
               0 => 'dealer_id',
               1 => 'task_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createForeignKey('activity_task_result', 'activity_task_result_dealer_id_dealers_id', array(
             'name' => 'activity_task_result_dealer_id_dealers_id',
             'local' => 'dealer_id',
             'foreign' => 'id',
             'foreignTable' => 'dealers',
             ));
        $this->createForeignKey('activity_task_result', 'activity_task_result_task_id_activity_task_id', array(
             'name' => 'activity_task_result_task_id_activity_task_id',
             'local' => 'task_id',
             'foreign' => 'id',
             'foreignTable' => 'activity_task',
             ));
        $this->addIndex('activity_task_result', 'activity_task_result_dealer_id', array(
             'fields' => 
             array(
              0 => 'dealer_id',
             ),
             ));
        $this->addIndex('activity_task_result', 'activity_task_result_task_id', array(
             'fields' => 
             array(
              0 => 'task_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('activity_task_result', 'activity_task_result_dealer_id_dealers_id');
        $this->dropForeignKey('activity_task_result', 'activity_task_result_task_id_activity_task_id');
        $this->removeIndex('activity_task_result', 'activity_task_result_dealer_id', array(
             'fields' => 
             array(
              0 => 'dealer_id',
             ),
             ));
        $this->removeIndex('activity_task_result', 'activity_task_result_task_id', array(
             'fields' => 
             array(
              0 => 'task_id',
             ),
             ));
        $this->dropTable('activity_task_result');
    }
}