<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddModelBlanksTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('agreement_model_blank', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'activity_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'model_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createForeignKey('agreement_model_blank', 'agreement_model_blank_activity_id_activity_id', array(
             'name' => 'agreement_model_blank_activity_id_activity_id',
             'local' => 'activity_id',
             'foreign' => 'id',
             'foreignTable' => 'activity',
             ));
        $this->createForeignKey('agreement_model_blank', 'agreement_model_blank_model_type_id_agreement_model_type_id', array(
             'name' => 'agreement_model_blank_model_type_id_agreement_model_type_id',
             'local' => 'model_type_id',
             'foreign' => 'id',
             'foreignTable' => 'agreement_model_type',
             ));
        $this->addIndex('agreement_model_blank', 'agreement_model_blank_activity_id', array(
             'fields' => 
             array(
              0 => 'activity_id',
             ),
             ));
        $this->addIndex('agreement_model_blank', 'agreement_model_blank_model_type_id', array(
             'fields' => 
             array(
              0 => 'model_type_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('agreement_model_blank', 'agreement_model_blank_activity_id_activity_id');
        $this->dropForeignKey('agreement_model_blank', 'agreement_model_blank_model_type_id_agreement_model_type_id');
        $this->removeIndex('agreement_model_blank', 'agreement_model_blank_activity_id', array(
             'fields' => 
             array(
              0 => 'activity_id',
             ),
             ));
        $this->removeIndex('agreement_model_blank', 'agreement_model_blank_model_type_id', array(
             'fields' => 
             array(
              0 => 'model_type_id',
             ),
             ));
        $this->dropTable('agreement_model_blank');
    }
}