<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddFormatHintForModelFields extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('agreement_model_field', 'format_hint', 'string', '255', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('agreement_model_field', 'format_hint');
    }
}