<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddRequiredFlagAndRightFormatForModelFields extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('agreement_model_field', 'required', 'boolean', '25', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->addColumn('agreement_model_field', 'right_format', 'string', '255', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('agreement_model_field', 'required');
        $this->removeColumn('agreement_model_field', 'right_format');
    }
}