<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddModelComments extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('agreement_comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'comment' => 
             array(
              'type' => 'clob',
              'notnull' => '',
              'length' => '',
             ),
             'request' => 
             array(
              'type' => 'clob',
              'notnull' => '',
              'length' => '',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
              3 => 'not_sent',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
              'status' => 
              array(
              'fields' => 
              array(
               0 => 'status',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('agreement_model_comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'comment' => 
             array(
              'type' => 'clob',
              'notnull' => '',
              'length' => '',
             ),
             'request' => 
             array(
              'type' => 'clob',
              'notnull' => '',
              'length' => '',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
              3 => 'not_sent',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
              'status' => 
              array(
              'fields' => 
              array(
               0 => 'status',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createForeignKey('agreement_model_comment', 'agreement_model_comment_user_id_user_id', array(
             'name' => 'agreement_model_comment_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->addIndex('agreement_model_comment', 'agreement_model_comment_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('agreement_model_comment', 'agreement_model_comment_user_id_user_id');
        $this->removeIndex('agreement_model_comment', 'agreement_model_comment_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->dropTable('agreement_comment');
        $this->dropTable('agreement_model_comment');
    }
}