<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RemoveNotSentStatusFromSpecialistComment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('agreement_comment', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
             ),
             'notnull' => '1',
             ));
        $this->changeColumn('agreement_model_comment', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
             ),
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('agreement_comment', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
              3 => 'not_sent'
             ),
             'notnull' => '1',
             ));
        $this->changeColumn('agreement_model_comment', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
              3 => 'not_sent'
             ),
             'notnull' => '1',
             ));
    }
}