<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSortingIndexForActivity extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('activity', 'sort', array(
             'fields' => 
             array(
              'finished', 'importance', 'sort', 'id'
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('activity', 'sort', array(
             'fields' => 
             array(
              'finished', 'importance', 'sort', 'id'
             ),
        ));
    }
}