<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddAgreementNotificationContol extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'agreement_notification', 'boolean', '25', array(
             'default' => '1',
             'notnull' => '1',
             ));
        $this->addIndex('user', 'agreement_notification', array(
             'fields' => 
             array(
              0 => 'agreement_notification',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('user', 'agreement_notification', array(
             'fields' => 
             array(
              0 => 'agreement_notification',
             ),
             ));
        $this->removeColumn('user', 'agreement_notification');
    }
}