<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddDealerBonus extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('dealer_bonus', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'dealer_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'year' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '2',
             ),
             'quarter' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '1',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
              'year' => 
              array(
              'fields' => 
              array(
               0 => 'year',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createForeignKey('dealer_bonus', 'dealer_bonus_dealer_id_dealers_id', array(
             'name' => 'dealer_bonus_dealer_id_dealers_id',
             'local' => 'dealer_id',
             'foreign' => 'id',
             'foreignTable' => 'dealers',
             ));
        $this->addIndex('dealer_bonus', 'dealer_bonus_dealer_id', array(
             'fields' => 
             array(
              0 => 'dealer_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dealer_bonus', 'dealer_bonus_dealer_id_dealers_id');
        $this->removeIndex('dealer_bonus', 'dealer_bonus_dealer_id', array(
             'fields' => 
             array(
              0 => 'dealer_id',
             ),
             ));
        $this->dropTable('dealer_bonus');
    }
}