<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RenameConceptTables extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('agreement_concept');
        $this->dropTable('agreement_concept_comment');
        $this->dropTable('agreement_concept_decline_reason');
        $this->createTable('concept', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'file' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wait',
              1 => 'wait_specialist',
              2 => 'accepted',
              3 => 'declined',
              4 => 'not_sent',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'activity_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'dealer_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'agreement_comments' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'agreement_comments_file' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'discussion_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'decline_reason_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('concept_comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'concept_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
              'status' => 
              array(
              'fields' => 
              array(
               0 => 'status',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('concept_decline_reason', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
         $this->createForeignKey('concept', 'concept_activity_id_activity_id', array(
             'name' => 'concept_activity_id_activity_id',
             'local' => 'activity_id',
             'foreign' => 'id',
             'foreignTable' => 'activity',
             ));
        $this->createForeignKey('concept', 'concept_dealer_id_dealers_id', array(
             'name' => 'concept_dealer_id_dealers_id',
             'local' => 'dealer_id',
             'foreign' => 'id',
             'foreignTable' => 'dealers',
             ));
        $this->createForeignKey('concept', 'concept_decline_reason_id_concept_decline_reason_id', array(
             'name' => 'concept_decline_reason_id_concept_decline_reason_id',
             'local' => 'decline_reason_id',
             'foreign' => 'id',
             'foreignTable' => 'concept_decline_reason',
             ));
        $this->createForeignKey('concept', 'concept_discussion_id_discussion_id', array(
             'name' => 'concept_discussion_id_discussion_id',
             'local' => 'discussion_id',
             'foreign' => 'id',
             'foreignTable' => 'discussion',
             ));
        $this->createForeignKey('concept_comment', 'concept_comment_concept_id_concept_id', array(
             'name' => 'concept_comment_concept_id_concept_id',
             'local' => 'concept_id',
             'foreign' => 'id',
             'foreignTable' => 'concept',
             ));
        $this->createForeignKey('concept_comment', 'concept_comment_user_id_user_id', array(
             'name' => 'concept_comment_user_id_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->addIndex('concept', 'concept_activity_id', array(
             'fields' => 
             array(
              0 => 'activity_id',
             ),
             ));
        $this->addIndex('concept', 'concept_dealer_id', array(
             'fields' => 
             array(
              0 => 'dealer_id',
             ),
             ));
        $this->addIndex('concept', 'concept_decline_reason_id', array(
             'fields' => 
             array(
              0 => 'decline_reason_id',
             ),
             ));
        $this->addIndex('concept', 'concept_discussion_id', array(
             'fields' => 
             array(
              0 => 'discussion_id',
             ),
             ));
        $this->addIndex('concept_comment', 'concept_comment_concept_id', array(
             'fields' => 
             array(
              0 => 'concept_id',
             ),
             ));
        $this->addIndex('concept_comment', 'concept_comment_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('concept', 'concept_activity_id_activity_id');
        $this->dropForeignKey('concept', 'concept_dealer_id_dealers_id');
        $this->dropForeignKey('concept', 'concept_decline_reason_id_concept_decline_reason_id');
        $this->dropForeignKey('concept', 'concept_discussion_id_discussion_id');
        $this->dropForeignKey('concept_comment', 'concept_comment_concept_id_concept_id');
        $this->dropForeignKey('concept_comment', 'concept_comment_user_id_user_id');
        $this->removeIndex('concept', 'concept_activity_id', array(
             'fields' => 
             array(
              0 => 'activity_id',
             ),
             ));
        $this->removeIndex('concept', 'concept_dealer_id', array(
             'fields' => 
             array(
              0 => 'dealer_id',
             ),
             ));
        $this->removeIndex('concept', 'concept_decline_reason_id', array(
             'fields' => 
             array(
              0 => 'decline_reason_id',
             ),
             ));
        $this->removeIndex('concept', 'concept_discussion_id', array(
             'fields' => 
             array(
              0 => 'discussion_id',
             ),
             ));
        $this->removeIndex('concept_comment', 'concept_comment_concept_id', array(
             'fields' => 
             array(
              0 => 'concept_id',
             ),
             ));
        $this->removeIndex('concept_comment', 'concept_comment_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->createTable('agreement_concept', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'file' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wait',
              1 => 'wait_specialist',
              2 => 'accepted',
              3 => 'declined',
              4 => 'not_sent',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'activity_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'dealer_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'agreement_comments' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'agreement_comments_file' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             'discussion_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'decline_reason_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->createTable('agreement_concept_comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wait',
              1 => 'accepted',
              2 => 'declined',
              ),
              'notnull' => '1',
              'length' => '',
             ),
             'concept_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
              'status' => 
              array(
              'fields' => 
              array(
               0 => 'status',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('agreement_concept_decline_reason', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('concept');
        $this->dropTable('concept_comment');
        $this->dropTable('concept_decline_reason');
        
   }
}