<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddConceptReportNotificationFields extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'agreement_concept_report_notification', 'boolean', '25', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->addColumn('user', 'new_agreement_concept_report_notification', 'boolean', '25', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->addColumn('user', 'final_agreement_concept_report_notification', 'boolean', '25', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->addIndex('user', 'agreement_concept_report_notification', array(
             'fields' => 
             array(
              0 => 'agreement_concept_report_notification',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('user', 'agreement_concept_report_notification', array(
             'fields' => 
             array(
              0 => 'agreement_concept_report_notification',
             ),
             ));
        $this->removeColumn('user', 'agreement_concept_report_notification');
        $this->removeColumn('user', 'new_agreement_concept_report_notification');
        $this->removeColumn('user', 'final_agreement_concept_report_notification');
    }
}