<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddAcceptDateForActivity extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('accepted_dealer_activity', 'accept_date', 'timestamp', '25', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('accepted_dealer_activity', 'accept_date');
    }
}