<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddActivityInfo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('activity_info', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'activity_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'icon' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'text' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'sort' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
              'sort' => 
              array(
              'fields' => 
              array(
               0 => 'activity_id',
               1 => 'sort',
               2 => 'id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createForeignKey('activity_info', 'activity_info_activity_id_activity_id', array(
             'name' => 'activity_info_activity_id_activity_id',
             'local' => 'activity_id',
             'foreign' => 'id',
             'foreignTable' => 'activity',
             ));
        $this->addIndex('activity_info', 'activity_info_activity_id', array(
             'fields' => 
             array(
              0 => 'activity_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('activity_info', 'activity_info_activity_id_activity_id');
        $this->removeIndex('activity_info', 'activity_info_activity_id', array(
             'fields' => 
             array(
              0 => 'activity_id',
             ),
             ));
        $this->dropTable('activity_info');
    }
}