<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIndexForAcceptActivityDate extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('accepted_dealer_activity', 'accept_date', array(
             'fields' => 
             array(
              0 => 'accept_date',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('accepted_dealer_activity', 'accept_date', array(
             'fields' => 
             array(
              0 => 'accept_date',
             ),
             ));
    }
}