all:
  stylesheets: [manager, fancybox/jquery.fancybox.min.css,pace/pace-theme-minimal.css]
  javascripts:
    - plugins/loaders/pace.min.js
    - activity/activity_quarters_data.js
    - activity/efficiency/activity_efficiency_graph_arrow.js
    - libs/jquery.animateNumber.min.js
    - plugins/tinymce/tinymce.min.js
    - fancybox/jquery.fancybox.min.js
    - activity/consolidated_information.js

