generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UserDealers
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_dealers
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        dealer_id: { label: Дилер }
      list:    ~
      filter:  ~
      form:    ~
      edit:    
        title: Изменить дилера
      new:     
        title: Добавить дилера
