generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ActivityFile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          activity_file
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        name: { label: Название }
      list:    ~
      filter:  ~
      form:    ~
      edit:   
        title: Файл "%%name%%"
      new:     
        title: Новый файл
